#!/bin/python3
#code starts here

# Asking what calculation should be done!
print("What kind of calculation you want to do?\n (a)add\n (s)sub\n (m)multiply\n (d)div\n")

# Assigning variable to take input!

value= input("select by a,s,m or d\n")

# Start of if/elif ladder!

if (value=="a"):
    no_1=int(input("Enter 1st no.\n"))
    no_2=int(input("Enter 2nd no.\n"))
    add = no_1 + no_2
    print(add)

elif (value=="s"):
    no_1=int(input("Enter 1st no.\n"))
    no_2=int(input("Enter 2nd no.\n"))
    sub = no_1 - no_2
    print(sub)

elif (value=="m"):
    no_1=int(input("Enter 1st no.\n"))
    no_2=int(input("Enter 2nd no.\n"))
    multiply = no_1 * no_2
    print(multiply)

elif (value=="d"):
    no_1=int(input("Enter 1st no.(dividend)\n"))
    no_2=int(input("Enter 2nd no.(divisor)\n"))
    if no_1 == 0 or no_2 == 0:
        print("cannot divide with 0\n")
    else:
        div = no_1 / no_2
        print(div)

else:
    print("wrong option\n")
    
#Ending
