#!/bin/python3
import os


print("Termux Or Linux?")

question= input('$ ')

if (question=="Linux"):
	print("Which Linux")
	which= input('$ Linux ')
	if (which== 'Void'):
	    os.system('sudo xbps-install python3 -y')
	    os.system('sudo mv calc /usr/bin')
	    os.system('sudo chmod +x $PREFIX/bin/calc')
	if (which== 'Ubuntu'):
	    os.system('sudo apt update')
	    os.system('sudo apt install python3 -y')
	    os.system('sudo mv calc /usr/bin')
	    os.system('sudo chmod +x $PREFIX/bin/calc')
	if (which== 'Arch'):
	    os.system('sudo pacman -Syy')
	    os.system('sudo pacman -S python3')
	    os.system('sudo mv calc /usr/bin')
	    os.system('sudo chmod +x $PREFIX/bin/calc')
if (question=="Termux"):
	os.system('apt update')
	os.system('apt install python3 -y')
	os.system('mv calc $PREFIX/bin')
	os.system('chmod +x $PREFIX/bin/calc')
	
else:
    print("Wrong Option")
    exit()
